/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-03-31 16:56:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.IOException;
import java.io.File;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Objects;
import java.util.Set;
import java.util.regex.Pattern;
import org.opengrok.indexer.configuration.RuntimeEnvironment;
import org.opengrok.indexer.history.History;
import org.opengrok.indexer.history.HistoryEntry;
import org.opengrok.indexer.history.HistoryGuru;
import org.opengrok.indexer.logger.LoggerFactory;
import org.opengrok.indexer.util.ForbiddenSymlinkException;
import org.opengrok.indexer.web.QueryParameters;
import org.opengrok.indexer.web.SearchHelper;
import org.opengrok.indexer.web.Util;
import org.opengrok.indexer.Info;
import org.opengrok.indexer.web.PageConfig;
import org.opengrok.indexer.web.Prefix;
import org.opengrok.indexer.web.Scripts;
import org.opengrok.indexer.web.PageConfig;
import org.opengrok.indexer.configuration.Project;
import org.opengrok.indexer.web.PageConfig;
import org.opengrok.indexer.web.Prefix;
import org.opengrok.indexer.web.QueryParameters;
import org.opengrok.indexer.web.Util;
import java.util.Date;
import java.util.EnumSet;
import org.opengrok.indexer.Info;
import org.opengrok.indexer.web.PageConfig;
import org.opengrok.indexer.web.Prefix;

public final class history_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


/* ---------------------- foot.jspf members start --------------------- */
    private static EnumSet<Prefix> needAddDiv = EnumSet.of(
        Prefix.HIST_L, Prefix.XREF_P, Prefix.DIFF_P, Prefix.MORE_P,
        // could NOT find any mapping/reference to those ones:
        Prefix.HIST_S, Prefix.XREF_S, Prefix.DIFF_S, Prefix.MORE_S);
/* ---------------------- foot.jspf members end --------------------- */

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/foot.jspf", Long.valueOf(1585243402000L));
    _jspx_dependants.put("/minisearch.jspf", Long.valueOf(1585243402000L));
    _jspx_dependants.put("/httpheader.jspf", Long.valueOf(1585243402000L));
    _jspx_dependants.put("/pageheader.jspf", Long.valueOf(1585243402000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.opengrok.indexer.web.Scripts");
    _jspx_imports_classes.add("java.text.Format");
    _jspx_imports_classes.add("org.opengrok.indexer.web.QueryParameters");
    _jspx_imports_classes.add("org.opengrok.indexer.web.SearchHelper");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("org.opengrok.indexer.configuration.Project");
    _jspx_imports_classes.add("org.opengrok.indexer.util.ForbiddenSymlinkException");
    _jspx_imports_classes.add("java.util.logging.Level");
    _jspx_imports_classes.add("org.opengrok.indexer.configuration.RuntimeEnvironment");
    _jspx_imports_classes.add("org.opengrok.indexer.web.Util");
    _jspx_imports_classes.add("org.opengrok.indexer.web.PageConfig");
    _jspx_imports_classes.add("java.util.EnumSet");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("java.io.IOException");
    _jspx_imports_classes.add("org.opengrok.indexer.history.HistoryEntry");
    _jspx_imports_classes.add("java.util.logging.Logger");
    _jspx_imports_classes.add("org.opengrok.indexer.Info");
    _jspx_imports_classes.add("java.io.File");
    _jspx_imports_classes.add("java.util.Objects");
    _jspx_imports_classes.add("org.opengrok.indexer.web.Prefix");
    _jspx_imports_classes.add("org.opengrok.indexer.history.History");
    _jspx_imports_classes.add("org.opengrok.indexer.logger.LoggerFactory");
    _jspx_imports_classes.add("java.util.regex.Pattern");
    _jspx_imports_classes.add("org.opengrok.indexer.history.HistoryGuru");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

/* ---------------------- history.jsp start --------------------- */
{
    final Logger LOGGER = LoggerFactory.getLogger(getClass());

    PageConfig cfg = PageConfig.get(request);
    cfg.checkSourceRootExistence();

    // Need to set the title before including httpheader.jspf
    cfg.setTitle(cfg.getHistoryTitle());

    String path = cfg.getPath();

    if (path.length() > 0) {
        String primePath = path;
        Project project = cfg.getProject();
        if (project != null) {
            SearchHelper searchHelper = cfg.prepareInternalSearch();
            /*
             * N.b. searchHelper.destroy() is called via
             * WebappListener.requestDestroyed() on presence of the following
             * REQUEST_ATTR.
             */
            request.setAttribute(SearchHelper.REQUEST_ATTR, searchHelper);
            searchHelper.prepareExec(project);

            try {
                primePath = searchHelper.getPrimeRelativePath(project.getName(), path);
            } catch (IOException | ForbiddenSymlinkException ex) {
                LOGGER.log(Level.WARNING, String.format(
                        "Error getting prime relative for %s", path), ex);
            }
        }

        File file = cfg.getResourceFile(primePath);
        History hist;
        try {
            hist = HistoryGuru.getInstance().getHistoryUI(file);
        } catch (Exception e) {
            // should not happen
            response.sendError(HttpServletResponse.SC_NOT_FOUND, e.getMessage());
            return;
        }

        if (hist == null) {
            /*
             * The history is not available even for a renamed file.
             * Send 404 Not Found.
             */
            response.sendError(HttpServletResponse.SC_NOT_FOUND);
            return;
        }
        request.setAttribute("history.jsp-hist", hist);
    }
}


/* ---------------------- httpheader.jsp start --------------------- */
{
    PageConfig cfg = PageConfig.get(request);
    String styleDir = cfg.getCssDir();
    String ctxPath = request.getContextPath();
    String dstyle = styleDir + '/' + "style-1.0.0.min.css";
    String pstyle = styleDir + '/' + "print-1.0.0.min.css";
    String mstyle = styleDir + '/' + "mandoc-1.0.0.min.css";

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\"\n");
      out.write("      class=\"");
      out.print( request.getServletPath().length() > 0 ? request.getServletPath().substring(1) : "" );
      out.write("\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"robots\" content=\"noindex,nofollow\" />\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n");
      out.write("<meta name=\"generator\" content=\"{OpenGrok ");
      out.print(Info.getVersion());
      out.write(' ');
      out.write('(');
      out.print(Info.getRevision());
      out.write(")\" />\n");
      out.write("<link rel=\"icon\" href=\"");
      out.print(styleDir);
      out.write("/img/icon.png\" type=\"image/png\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"all\"\n");
      out.write("    title=\"Default\" href=\"");
      out.print( dstyle );
      out.write("\" />\n");
      out.write("<link rel=\"alternate stylesheet\" type=\"text/css\" media=\"all\"\n");
      out.write("    title=\"Paper White\" href=\"");
      out.print( pstyle );
      out.write("\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( mstyle );
      out.write("\" media=\"all\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( pstyle );
      out.write("\" media=\"print\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(styleDir);
      out.write("/jquery-ui-1.12.1-custom.min.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(styleDir);
      out.write("/jquery-ui-1.12.1-custom.structure.min.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(styleDir);
      out.write("/jquery-ui-1.12.1-custom.theme.min.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(styleDir);
      out.write("/jquery.tooltip.min.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(styleDir);
      out.write("/jquery.tablesorter.min.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(styleDir);
      out.write("/searchable-option-list-2.0.3.min.css\" />\n");
      out.write("\n");

    /**
     * The order can be arbitrary here, it is hardcoded in Scripts. These
     * are printed out in footer.
     *
     * @see Scripts
     */
    cfg.addScript("jquery");
    cfg.addScript("jquery-ui");
    cfg.addScript("jquery-tablesorter");
    cfg.addScript("tablesorter-parsers");
    cfg.addScript("searchable-option-list");
    cfg.addScript("utils");
    cfg.addScript("jquery-caret");

if (cfg.getPrefix().equals(Prefix.HIST_L)) {
    out.write("<link rel=\"alternate\" type=\"application/rss+xml\" " +
        "title=\"RSS feed for " + cfg.getPath() + "\" " +
        "href=\"" + ctxPath + Prefix.RSS_P + cfg.getPath() + "\" />");
}

      out.write("<link rel=\"search\" href=\"");
      out.print(ctxPath);
      out.write("/opensearch\"\n");
      out.write("    type=\"application/opensearchdescription+xml\"\n");
      out.write("    title=\"OpenGrok Search for current project(s)\" />\n");
      out.write("<script type=\"text/javascript\">/* <![CDATA[ */\n");
      out.write("    window.contextPath = '");
      out.print( ctxPath );
      out.write("';\n");
      out.write("    document.xrefPath = '");
      out.print( request.getContextPath() + Prefix.XREF_P );
      out.write("';\n");
      out.write("    document.pageReady = [];\n");
      out.write("    document.domReady = [];\n");
      out.write("/* ]]> */\n");
      out.write("</script>\n");
      out.print( cfg.getEnv().getIncludeFiles().getHttpHeaderIncludeFileContent(false) );
      out.write("<title>");
      out.print(cfg.getTitle());
      out.write("</title>");

    out.write(cfg.getHeaderData());

      out.write("</head>");

}
/* ---------------------- httpheader.jsp end --------------------- */


{
    if ((request.getAttribute("history.jsp-hist")) != null) {

      out.write("<body>\n");
      out.write("<script type=\"text/javascript\">/* <![CDATA[ */\n");
      out.write("    document.rev = function() { return getParameter(\"");
      out.print( QueryParameters.REVISION_PARAM );
      out.write("\"); };\n");
      out.write("    document.annotate = ");
      out.print( PageConfig.get(request).annotate() );
      out.write(";\n");
      out.write("    document.domReady.push(function() { domReadyMast(); });\n");
      out.write("    document.pageReady.push(function() { pageReadyMast(); });\n");
      out.write("/* ]]> */</script>\n");
      out.write("<div id=\"page\">\n");
      out.write("    <div id=\"whole_header\">\n");
      out.write("        <div id=\"header\">\n");

    }
}
{
    if (request.getAttribute("history.jsp-hist") != null) {


/* ---------------------- pageheader.jspf start --------------------- */
{
    PageConfig cfg = PageConfig.get(request);

      out.print( cfg.getEnv().getIncludeFiles().getHeaderIncludeFileContent(false) );
 
}
/* ---------------------- pageheader.jspf end --------------------- */


    }
}
{
    PageConfig cfg = PageConfig.get(request);
    String context = request.getContextPath();
    String path = cfg.getPath();

    History hist;
    if ((hist = (History) request.getAttribute("history.jsp-hist")) != null) {

        int start = cfg.getSearchStart();
        int max = cfg.getSearchMaxItems();
        long totalHits = hist.getHistoryEntries().size();
        long thispage = Math.min(totalHits - start, max);

        // We have a lots of results to show: create a slider for them
        request.setAttribute("history.jsp-slider", Util.createSlider(start, max, totalHits, request));

      out.write("</div>\n");
      out.write("        <div id=\"Masthead\">History log of \n");
      out.write("        ");
      out.print( Util.breadcrumbPath(context + Prefix.XREF_P, path,'/',"",true,cfg.isDir()) );
      out.write("\n");
      out.write("        (Results <b> ");
      out.print( totalHits != 0 ? start + 1 : 0 );
      out.write(' ');
      out.write('–');
      out.write(' ');
      out.print( thispage + start
            );
      out.write("</b> of <b>");
      out.print( totalHits );
      out.write("</b>)\n");
      out.write("        </div>\n");

    }
}
{
    if (request.getAttribute("history.jsp-hist") != null) {


    /* ---------------------- minisearch.jspf start --------------------- */
{
        PageConfig cfg = PageConfig.get(request);
        String context = request.getContextPath();

      out.write("<form action=\"");
      out.print( context + Prefix.SEARCH_P );
      out.write("\">\n");
      out.write("<div id=\"bar\">\n");
      out.write("    <ul>\n");
      out.write("        <li><a href=\"");
      out.print( context );
      out.write("/\"><span id=\"home\"></span>Home</a></li>");

    if (cfg.getEnv().isHistoryEnabled()) {
        if (!cfg.hasHistory()) {
            
      out.write("<li><span id=\"history\"></span><span class=\"c\">History</span></li>");

        } else {
            
      out.write("<li><a href=\"");
      out.print( context + Prefix.HIST_L + cfg.getUriEncodedPath()
                );
      out.write("\"><span id=\"history\"></span>History</a></li>");

        }
    }
    if (!cfg.hasAnnotations() /* || cfg.getPrefix() == Prefix.HIST_S */ ) {
        
      out.write("<li><span class=\"c\"><span class=\"annotate\"></span>Annotate</span></li>");

    } else if (cfg.annotate()) {
        
      out.write("<li><span id=\"toggle-annotate-by-javascript\" style=\"display: none\"><a\n");
      out.write("            href=\"#\" onclick=\"javascript:toggle_annotations(); return false;\"\n");
      out.write("            title=\"Show or hide line annotation (revisions, authors).\"\n");
      out.write("            ><span class=\"annotate\"></span>Annotate</a></span><span\n");
      out.write("            id=\"toggle-annotate\"><a href=\"#\"><span class=\"annotate\"></span>\n");
      out.write("            Annotate</a></span></li>");

    } else if (cfg.getPrefix() == Prefix.HIST_L) {
        
      out.write("<li>\n");
      out.write("            <a href=\"#\"\n");
      out.write("               onclick=\"javascript:\n");
      out.write("                           window.location = '");
      out.print( context + Prefix.XREF_P + cfg.getUriEncodedPath() );
      out.write("'\n");
      out.write("                           // taken from get_annotations() from utils.js\n");
      out.write("                           + '?");
      out.print( QueryParameters.ANNOTATION_PARAM_EQ_TRUE );
      out.write("'\n");
      out.write("                           + (document.rev && document.rev() ?\n");
      out.write("                                   '&amp;");
      out.print( QueryParameters.REVISION_PARAM_EQ );
      out.write("'\n");
      out.write("                           + encodeURIComponent(document.rev()) : '')\n");
      out.write("                           + (window.location.hash ?\n");
      out.write("                                   '&amp;");
      out.print( QueryParameters.WINDOW_HASH_PARAM_EQ );
      out.write("'\n");
      out.write("                           + window.location.hash.substring(1, window.location.hash.length) : '');\n");
      out.write("                           return false;\">\n");
      out.write("                <span class=\"annotate\"></span>\n");
      out.write("                Annotate\n");
      out.write("            </a>\n");
      out.write("        </li>");

    } else {
        
      out.write("<li><a href=\"#\" onclick=\"javascript:get_annotations(); return false;\"\n");
      out.write("            ><span class=\"annotate\"></span>Annotate</a></li>");

    }
    if (!cfg.isDir()) {
        if (cfg.getPrefix() == Prefix.XREF_P) {
        
      out.write("<li><a href=\"#\" onclick=\"javascript:lntoggle();return false;\"\n");
      out.write("            title=\"Show or hide line numbers (might be slower if file has more than 10 000 lines).\">\n");
      out.write("              <span id=\"line\"></span>Line#</a></li>\n");
      out.write("          <li><a href=\"#\" class=\"scopes-toggle\"\n");
      out.write("            title=\"Show or hide scopes window.\">\n");
      out.write("              <span id=\"line\">");
      out.write("</span>Scopes#</a></li>\n");
      out.write("        <li><a href=\"#\" id=\"navigate\"\n");
      out.write("            title=\"Show or hide symbol list.\">\n");
      out.write("              <span id=\"defbox\"></span>Navigate#</a></li>");

        }
        
      out.write("<li><a href=\"");
      out.print( context + Prefix.RAW_P + cfg.getUriEncodedPath() +
            (cfg.getRequestedRevision().length() == 0 ? "" : "?" +
            QueryParameters.REVISION_PARAM_EQ + Util.URIEncode(cfg.getRequestedRevision()))
            );
      out.write("\"><span id=\"raw\"></span>Raw</a></li>\n");
      out.write("\t<li><a href=\"");
      out.print( context + Prefix.DOWNLOAD_P + cfg.getUriEncodedPath() +
            (cfg.getRequestedRevision().length() == 0 ? "" : "?" +
            QueryParameters.REVISION_PARAM_EQ + Util.URIEncode(cfg.getRequestedRevision()))
            );
      out.write("\"><span id=\"download\"></span>Download</a></li>\n");
      out.write("\t");

    }
        
      out.write("<li><input type=\"text\" id=\"search\" name=\"");
      out.print( QueryParameters.FULL_SEARCH_PARAM );
      out.write("\"\n");
      out.write("                  class=\"q\" /></li>\n");
      out.write("            <li><input type=\"submit\" value=\"Search\" class=\"submit\" /></li>");

    Project proj = cfg.getProject();
    String[] vals = cfg.getSearchOnlyIn();
        
      out.write("<li><input id=\"minisearch-path\" type=\"checkbox\"\n");
      out.write("                  name=\"");
      out.print( QueryParameters.PATH_SEARCH_PARAM );
      out.write("\" value='\"");
      out.print( vals[0]
            );
      out.write('"');
      out.write('\'');
      out.write(' ');
      out.print( vals[2] );
      out.write("/> current directory</li>\n");
      out.write("    </ul>");

    if (proj != null) {
    
      out.write("<input id=\"minisearch-project\" type=\"hidden\" name=\"");
      out.print( QueryParameters.PROJECT_SEARCH_PARAM );
      out.write("\"\n");
      out.write("           value=\"");
      out.print(proj.getName());
      out.write("\" />");

    }

      out.write("<input type=\"hidden\" id=\"contextpath\" value=\"");
      out.print(request.getContextPath());
      out.write("\" />\n");
      out.write("</div>\n");
      out.write("        </form>\n");
      out.write("        <script type=\"text/javascript\">/* <![CDATA[ */\n");
      out.write("            document.domReady.push(function() { domReadyMenu(true); });\n");
      out.write("            /* ]]> */\n");
      out.write("        </script>\n");
      out.write("    </div>\n");
      out.write("<div id=\"content\">\n");
 
}
/* ---------------------- minisearch.jspf end --------------------- */


    }
}
{
    PageConfig cfg = PageConfig.get(request);
    String context = request.getContextPath();
    String path = cfg.getPath();
    History hist;
    if ((hist = (History) request.getAttribute("history.jsp-hist")) != null) {
        RuntimeEnvironment env = cfg.getEnv();
        String uriEncodedName = cfg.getUriEncodedPath();

        boolean striked = false;
        String userPage = env.getUserPage();
        String userPageSuffix = env.getUserPageSuffix();
        String bugPage = env.getBugPage();
        String bugRegex = env.getBugPattern();
        Pattern bugPattern = Pattern.compile(bugRegex);
        String reviewPage = env.getReviewPage();
        String reviewRegex = env.getReviewPattern();
        Pattern reviewPattern = Pattern.compile(reviewRegex);

        Format df = new SimpleDateFormat("dd-MMM-yyyy");

        int revision2 = Math.max(cfg.getIntParam(QueryParameters.REVISION_2_PARAM, -1), 0);
        int revision1 = cfg.getIntParam(QueryParameters.REVISION_1_PARAM, -1) < revision2 ?
                revision2 + 1 : cfg.getIntParam(QueryParameters.REVISION_1_PARAM, -1);
        revision2 = revision2 >= hist.getHistoryEntries().size() ? hist.getHistoryEntries().size() - 1 : revision2;

        int start = cfg.getSearchStart();
        int max = cfg.getSearchMaxItems();

      out.write("<script type=\"text/javascript\">/* <![CDATA[ */\n");
      out.write("document.domReady.push(function() {domReadyHistory();});\n");
      out.write("/* ]]> */</script>\n");
      out.write("<!--[if IE]>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("  table#revisions tbody tr td p {\n");
      out.write("        word-break: break-all;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("<![endif]-->\n");
      out.write("<form action=\"");
      out.print( context + Prefix.DIFF_P + uriEncodedName );
      out.write("\">\n");
      out.write("<table class=\"src\" id=\"revisions\">\n");
      out.write("    <thead>\n");
      out.write("        <tr>\n");
      out.write("            <th>Revision ");

            if (hist.hasTags()) {
                
      out.write("<a href=\"#\" onclick=\"javascript: toggle_revtags(); return false;\">\n");
      out.write("                    <span class=\"revtags-hidden\">\n");
      out.write("                    (&lt;&lt;&lt; Hide revision tags)</span>\n");
      out.write("                    <span class=\"revtags\">\n");
      out.write("                    (Show revision tags &gt;&gt;&gt;)</span></a>");

            }
            
      out.write("</th>");

            if (!cfg.isDir()) {
            
      out.write("<th><input type=\"submit\" value=\" Compare \"/>\n");
      out.write("            ");
 if (hist.getHistoryEntries().size() > revision1 && revision1 >= 0) { 
      out.write("<input type=\"hidden\" id=\"input_r1\" name=\"");
      out.print( QueryParameters.REVISION_1_PARAM );
      out.write("\"\n");
      out.write("                value=\"");
      out.print( path + '@' + hist.getHistoryEntries().get(revision1).getRevision() );
      out.write("\"/>\n");
      out.write("            ");
 } 
 if (hist.getHistoryEntries().size() > revision2 && revision2 >= 0) { 
      out.write("<input type=\"hidden\" id=\"input_r2\" name=\"");
      out.print( QueryParameters.REVISION_2_PARAM );
      out.write("\"\n");
      out.write("                value=\"");
      out.print( path + '@' + hist.getHistoryEntries().get(revision2).getRevision() );
      out.write("\"/>\n");
      out.write("            ");
 } 
      out.write("</th>");

            }
            
      out.write("<th>Date</th>\n");
      out.write("            <th>Author</th>\n");
      out.write("            <th>Comments ");

            if (hist.hasFileList()) {
                
      out.write("<a href=\"#\" onclick=\"javascript: toggle_filelist(); return false;\">\n");
      out.write("                    <div class=\"filelist-hidden\">\n");
      out.write("                    (&lt;&lt;&lt; Hide modified files)</div>\n");
      out.write("                    <div class=\"filelist\">\n");
      out.write("                    (Show modified files &gt;&gt;&gt;)</div></a>");

            }
            
      out.write("</th>\n");
      out.write("        </tr>\n");
      out.write("    </thead>\n");
      out.write("    <tbody>\n");
      out.write("            ");

            int count=0;
            for (HistoryEntry entry : hist.getHistoryEntries(max, start)) {
                String rev = entry.getRevision();
                if (rev == null || rev.length() == 0) {
                    rev = "";
                }
                String tags = entry.getTags();

                if (tags != null) {
			int colspan;
			if (cfg.isDir())
				colspan = 4;
			else
				colspan = 5;
                    
      out.write("<tr class=\"revtags-hidden\">\n");
      out.write("            <td colspan=\"");
      out.print( colspan );
      out.write("\" class=\"revtags\">\n");
      out.write("                <b>Revision tags:</b> ");
      out.print( tags );
      out.write("</td>\n");
      out.write("        </tr><tr style=\"display: none;\"></tr>");

                }
    
      out.write("<tr>");

                if (cfg.isDir()) {
            
      out.write("<td>");
      out.print( rev );
      out.write("</td>");

                } else {
                    if (entry.isActive()) {
                        StringBuffer urlBuffer = request.getRequestURL();
                        if (request.getQueryString() != null) {
                            urlBuffer.append('?').append(request.getQueryString());
                        }
                        urlBuffer.append('#').append(rev);
            
      out.write("<td><a href=\"");
      out.print( urlBuffer );
      out.write("\"\n");
      out.write("                title=\"link to revision line\">#</a>\n");
      out.write("                <a href=\"");
      out.print( context + Prefix.XREF_P + uriEncodedName + "?" +
                        QueryParameters.REVISION_PARAM_EQ + Util.URIEncode(rev) );
      out.write('"');
      out.write('>');
      out.print( rev );
      out.write("</a></td>\n");
      out.write("            <td>");

                
      out.write("<input type=\"radio\"\n");
      out.write("                        data-revision-1=\"");
      out.print( (start + count) );
      out.write("\"\n");
      out.write("                        data-revision-2=\"");
      out.print( revision2 );
      out.write("\"\n");
      out.write("                        data-diff-revision=\"");
      out.print( QueryParameters.REVISION_1_PARAM );
      out.write("\"\n");
      out.write("                        data-revision-path=\"");
      out.print( path + '@' + hist.getHistoryEntries().get(start + count).getRevision());
      out.write("\"\n");
      out.write("                ");

                if (count + start > revision1 || (count + start > revision2 && count + start <= revision1 - 1)) {
                    // revision1 enabled
                } else if (count + start == revision1 ) {
                    // revision1 selected
                    
      out.write(" checked=\"checked\"");

                } else if( count + start <= revision2 ) {
                    // revision1 disabled
                    
      out.write(" disabled=\"disabled\" ");

                }
                
      out.write('/');
      out.write('>');


                
      out.write("<input type=\"radio\"\n");
      out.write("                        data-revision-1=\"");
      out.print( revision1 );
      out.write("\"\n");
      out.write("                        data-revision-2=\"");
      out.print( (start + count) );
      out.write("\"\n");
      out.write("                        data-diff-revision=\"");
      out.print( QueryParameters.REVISION_2_PARAM );
      out.write("\"\n");
      out.write("                        data-revision-path=\"");
      out.print( path + '@' + hist.getHistoryEntries().get(start + count).getRevision() );
      out.write("\"\n");
      out.write("                ");

                if( count + start < revision2 || (count + start > revision2 && count + start <= revision1 - 1) ) {
                    // revision2 enabled
                } else if( count + start == revision2 ) {
                    // revision2 selected
                    
      out.write(" checked=\"checked\" ");

                } else if (count + start >= revision1 ) {
                    // revision2 disabled
                    
      out.write(" disabled=\"disabled\" ");

                }
                
      out.write('/');
      out.write('>');

                
      out.write("</td>");

                    } else {
                        striked = true;
                
      out.write("<td><del>");
      out.print( rev );
      out.write("</del></td>\n");
      out.write("            <td></td>");

                    }
                }
            
      out.write("<td>");

                Date date = entry.getDate();
                if (date != null) {
            
      out.print( df.format(date) );

                }
                
      out.write("</td>\n");
      out.write("            <td>");

                String author = entry.getAuthor();
                if (author == null) {
                
      out.write("(no author)");

                } else if (userPage != null && userPage.length() > 0) {
		String alink = Util.getEmail(author);
                
      out.write("<a href=\"");
      out.print( userPage + Util.htmlize(alink) + userPageSuffix
                );
      out.write('"');
      out.write('>');
      out.print( Util.htmlize(author));
      out.write("</a>");

                } else {
                
      out.print( author );

                }
                
      out.write("</td>\n");
      out.write("            <td><a name=\"");
      out.print( rev );
      out.write("\"></a>");

                // revision message collapse threshold minimum of 10
                int summaryLength = Math.max(10, cfg.getRevisionMessageCollapseThreshold());
                String cout = Util.htmlize(entry.getMessage());

                if (bugPage != null && bugPage.length() > 0) {
                    cout = Util.linkifyPattern(cout, bugPattern, "$1", Util.completeUrl(bugPage + "$1", request));
                }
                if (reviewPage != null && reviewPage.length() > 0) {
                    cout = Util.linkifyPattern(cout, reviewPattern, "$1", Util.completeUrl(reviewPage + "$1", request));
                }
                
                boolean showSummary = false;
                String coutSummary = entry.getMessage();
                if (coutSummary.length() > summaryLength) {
                    showSummary = true;
                    coutSummary = coutSummary.substring(0, summaryLength - 1);
                    coutSummary = Util.htmlize(coutSummary);
                    if (bugPage != null && bugPage.length() > 0) {
                        coutSummary = Util.linkifyPattern(coutSummary, bugPattern, "$1", Util.completeUrl(bugPage + "$1", request));
                    }
                    if (reviewPage != null && reviewPage.length() > 0) {
                        coutSummary = Util.linkifyPattern(coutSummary, reviewPattern, "$1", Util.completeUrl(reviewPage + "$1", request));
                    }
                }

                if (showSummary) {
                    
      out.write("<p class=\"rev-message-summary\">");
      out.print( coutSummary );
      out.write("</p>\n");
      out.write("                    <p class=\"rev-message-full rev-message-hidden\">");
      out.print( cout );
      out.write("</p>\n");
      out.write("                    <p class=\"rev-message-toggle\" data-toggle-state=\"less\"><a class=\"rev-toggle-a\" href=\"#\">show more ... </a></p>\n");
      out.write("                    ");

                }
                else {
                     
      out.write("<p class=\"rev-message-full\">");
      out.print( cout );
      out.write("</p>");

                }

                Set<String> files = entry.getFiles();
                if (files != null) {
                
      out.write("<div class=\"filelist-hidden\"><br/>");

                    for (String ifile : files) {
                        String jfile = Util.stripPathPrefix(path, ifile);
                        if (Objects.equals(rev, "")) {
                
      out.write("<a class=\"h\" href=\"");
      out.print( context + Prefix.XREF_P + ifile );
      out.write('"');
      out.write('>');
      out.print( jfile );
      out.write("</a><br/>");

                        } else {
                
      out.write("<a class=\"h\" href=\"");
      out.print( context + Prefix.XREF_P + ifile );
      out.write('?');
      out.print( QueryParameters.REVISION_PARAM_EQ );
      out.print( rev );
      out.write('"');
      out.write('>');
      out.print( jfile );
      out.write("</a><br/>");

                        }
                    }
                
      out.write("</div>");

                }
                
      out.write("</td>\n");
      out.write("        </tr>");

                count++;
            }
        
      out.write("</tbody>\n");
      out.write("    <tfoot>\n");
      out.write("        <tr>\n");
      out.write("            <td colspan=\"5\">\n");

    String slider;
    if ((slider = (String) request.getAttribute("history.jsp-slider")) != null) {
        // NOTE: shouldn't happen that it doesn't have this attribute
        
      out.write("<p class=\"slider\">");
      out.print( slider );
      out.write("</p>");

    }

      out.write("</td>\n");
      out.write("        </tr>\n");
      out.write("    </tfoot>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("</form>");

            if (striked) {

      out.write("<p><b>Note:</b> No associated file changes are available for\n");
      out.write("revisions with strike-through numbers (eg. <del>1.45</del>)</p>");

            }

      out.write("<p class=\"rssbadge\"><a href=\"");
      out.print(context + Prefix.RSS_P + uriEncodedName
);
      out.write("\" title=\"RSS XML Feed of latest changes\"><span id=\"rssi\"></span></a></p>\n");
      out.write("\n");


    }
}
/* ---------------------- history.jsp end --------------------- */


/* ---------------------- foot.jspf start --------------------- */
{
    PageConfig cfg = PageConfig.get(request);
    Date dateForLastIndexRun = cfg.getEnv().getDateForLastIndexRun();
    
        
      out.write("<div id=\"footer\">\n");
      out.write("<p><a href=\"http://opengrok.github.com/OpenGrok/\"\n");
      out.write(" title=\"Served by OpenGrok (");
      out.print( Info.getVersion() );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print( Info.getShortRevision() );
      out.write(")\"><span id=\"fti\"></span></a></p>\n");
 if(dateForLastIndexRun != null) { 
      out.write("<p>Last Index update ");
      out.print( dateForLastIndexRun );
      out.write("</p>\n");
}
      out.print( cfg.getEnv().getIncludeFiles().getFooterIncludeFileContent(false) );

    if (needAddDiv.contains(cfg.getPrefix())) {
        
      out.write("</div>");
 // #content
    }
    // #footer, #page:
    
      out.write("</div>\n");
      out.write("</div>\n");

    /**
     * Print out all collected javascript files (or inline script) by the calls
     * to {@link PageConfig#addScript} methods.
     */

      out.print( PageConfig.get(request).getScripts() );
      out.write("</body>\n");
      out.write("</html>\n");

}
/* ---------------------- foot.jspf end --------------------- */

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
